// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dobjeeuzwipelgrcrmtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvYmplZXV6d2lwZWxncmNybXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjEwMzMsImV4cCI6MjA3MjEzNzAzM30.eSjCHIHzvswDy4JD0SyrSjYWQAEEX55bW0ZLwdifPaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});